project_id = "iljexuubiivpinictxlq"

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.ai-rewrite]
verify_jwt = false

[functions.extract-cv]
verify_jwt = false